### ISSUE TITLE
kind request to add the #franklin tab

### ISSUE THREAD

**Issue by tlienart** [fusion809/fusion809.github.io#1]
(feel free to close)

I had a request some time ago to encourage Franklin users to add the `#franklin` to their repo so that they could find examples more readily. If you don't mind that would be great otherwise no worries!

Thanks

**Comment by fusion809** [comment]
Sure, that's fine. I thought adding #franklin to this repo might make it seem like my project provides something to extend Franklin (e.g. a theme, a template, a package, or w/e), which is false of course. But if that's how it's being used, I'll be happy to.
