### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by amittos** [fusion809/fusion809.github.io#2]
I love your blog but I usually follow my favorite blogs via RSS (Feedly). I noticed that you don't have RSS enabled in The Hornery. Jekyll actually supports RSS (check here: http://jekyll.tips/jekyll-casts/rss-feed/). Can you enable it please?

**Comment by fusion809** [comment]
Thanks for the feedback. See #1 mate, though, this site has an [Atom feed](https://fusion809.github.io/feed), which to my knowledge is pretty much the same as RSS.

**Comment by amittos** [comment]
Yes it is. I've added it on Feedly already. Thank you :)

**Comment by fusion809** [comment]
So is this issue resolved? Just asking if I can close this issue.

**Comment by amittos** [comment]
Resolved indeed! Maybe you can put a link of the Atom reader in your website's menu (or somewhere else visible) for future requests. Thank you for the quick response. Keep writing awesome and thorough articles :)

**Comment by fusion809** [comment]
Ah, it is in the site footer. See in the area I enclosed with a red box in this screenshot of the website's footer. 
![deepinscreenshot20170113234233-boxed](https://cloud.githubusercontent.com/assets/4717341/21932049/497b311c-d9ea-11e6-99ce-f3381fe4e580.png)
