### ISSUE TITLE
please note there is an existing vim-appimage available now

### ISSUE THREAD

**Issue by chrisbra** [fusion809/fusion809.github.io#3]
See vim/vim-appimage repository.

**Comment by fusion809** [comment]
Yep I know, I followed that vim/vim AppImage issue. Not sure how it's relevant to this repo though, would have thought you'd report it at [fusion809/GVim.AppImage](https://github.com/fusion809/GVim.AppImage).

**Comment by chrisbra** [comment]
Oh, I didn't want to mean, you should not maintain your appimage repository anymore. I barely stumbled over your website https://fusion809.github.io/appimages/ and thought you want to mention that there is an official vim-appimage repository now available.

**Comment by fusion809** [comment]
Ah well that's done now (per https://github.com/fusion809/fusion809.github.io/commit/efa5642a5e07ec5251b18d9d28aec632ce158c7e) so I'm closing.
